---
kind: pipeline
name: build-android
type: docker
trigger:
  event:
    - tag
image_pull_secrets:
  - privatereg_docker_config
steps:
  - name: Retrieve signing certificate
    image: registry.systest.eu/ci-images/react-native-android-build:latest
    environment:
      ANDROID_KEYSTORE_BASE64:
        from_secret: android_keystore_base64
    commands:
      - echo $ANDROID_KEYSTORE_BASE64 | base64 -di > android/app/release.keystore
  - name: Install dependencies
    image: registry.systest.eu/ci-images/react-native-android-build:latest
    commands:
      - npm ci
  - name: Build
    image: registry.systest.eu/ci-images/react-native-android-build:latest
    environment:
      ANDROID_KEYSTORE: release.keystore
      ANDROID_KEYSTORE_PASSWORD:
        from_secret: android_keystore_password
    commands:
      - cd android
      - gradle assembleRelease
  - name: Github release APK
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_release_token
      title: Release ${DRONE_TAG}
      files:
        - android/app/build/outputs/apk/release/app-release.apk
---
kind: pipeline
name: build-server
type: docker
trigger:
  event:
    - tag
steps:
  - name: Install dependencies
    image: golang
    commands:
      - apt-get install -y gcc libc6-dev libx11-dev xorg-dev libxtst-dev
      - cd server
      - go get -v
  - name: Build Linux amd64
    image: golang
    environment:
      GOOS: linux
      GOARCH: amd64
    commands:
      - cd server
      - go build -o barcode-to-pc-server-$GOOS-$GOARCH
  - name: Build Darwin amd64
    image: golang
    environment:
      GOOS: darwin
      GOARCH: amd64
    commands:
      - cd server
      - go build -o barcode-to-pc-server-$GOOS-$GOARCH
  - name: Build Windows amd64
    image: golang
    environment:
      GOOS: windows
      GOARCH: amd64
    commands:
      - cd server
      - go build -o barcode-to-pc-server-$GOOS-$GOARCH.exe
  - name: Github release binaries
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_release_token
      title: Release ${DRONE_TAG}
      files:
        - server/barcode-to-pc-server-*
